// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'index',
    'basicconcepts',
    'gettingstarted',
    {
      type: 'category',
      label: 'Providers',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'provider' }],
    },
    {
      type: 'category',
      label: 'Cluster',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'cluster' }],
    },
    {
      type: 'category',
      label: 'Environment',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'environment' }],
    },
    {
      type: 'category',
      label: 'Project',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'project' }],
    },
    'connect_to_git',
    {
      type: 'category',
      label: 'Domain',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'domain' }],
    },
    {
      type: 'category',
      label: 'Network Resources',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'network' }],
    },
    {
      type: 'category',
      label: 'User',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'user' }],
    },
    'responsability-model',
    'cli',
    'changelog',
  ],
};

module.exports = sidebars;
